#!/bin/bash
#Mullvad Browser no firejail
echo "firejail --noprofile --novideo --ipc-namespace --machine-id ~/Downloads/mullvad-browser/Browser/start-mullvad-browser;";
firejail --noprofile --novideo --ipc-namespace --machine-id ~/Downloads/mullvad-browser/Browser/start-mullvad-browser;
