#!/bin/bash
#Mullvad Browser sem som e sem vídeo no firejail
echo "firejail --noprofile --nosound --novideo --ipc-namespace --machine-id ~/Downloads/mullvad-browser/Browser/start-mullvad-browser;";
firejail --noprofile --nosound --novideo --ipc-namespace --machine-id ~/Downloads/mullvad-browser/Browser/start-mullvad-browser;
