#!/bin/bash
#TorBrowser no firejail
echo "firejail --seccomp --ipc-namespace --machine-id --private-tmp ~/Downloads/tor-browser2/Browser/start-tor-browser;";
firejail --seccomp --ipc-namespace --machine-id --private-tmp ~/Downloads/tor-browser2/Browser/start-tor-browser;
